services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg16
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
volumes:
    postgresql-data: